- biome: ocean
  maxAltitude: -14
- biome: cursedashlands
  amount: 0.41
  minDistance: 0.8
  curveY: -0.4
- biome: ashlands
  minDistance: 0.8
  curveY: -0.4
- biome: cursedmountain
  amount: 0.41
  minAltitude: 40
- biome: mountain
  minAltitude: 40
- biome: curseddeepnorth
  amount: 0.41
  minDistance: 0.8
  curveY: 0.4
- biome: deepnorth
  minDistance: 0.8
  curveY: 0.4
- biome: cursedswamp
  maxAltitude: 20
  minAltitude: -20
  maxDistance: 0.8
  minDistance: 0.2
  amount: 0.26
  wiggleDistance: false
- biome: swamp
  maxAltitude: 20
  minAltitude: -20
  maxDistance: 0.8
  minDistance: 0.2
  amount: 0.4
  wiggleDistance: false
- biome: cursedmistlands
  minDistance: 0.6
  amount: 0.36
- biome: mistlands
  minDistance: 0.6
  amount: .7
- biome: cursedplains
  maxDistance: 0.8
  minDistance: 0.3
  amount: 0.36
- biome: plains
  maxDistance: 0.8
  minDistance: 0.3
  amount: 0.6
- biome: cursedblackforest
  maxDistance: 0.6
  minDistance: 0.06
  amount: 0.36
- biome: blackforest
  maxDistance: 0.6
  minDistance: 0.06
  amount: 0.6
- biome: cursedmeadows
  amount: 0.51
  maxDistance: 0.5
- biome: meadows
  maxDistance: 0.5
- biome: cursedblackforest
  amount: 0.41
- biome: blackforest
