- name: DG_ForestCrypt
  algorithm: Dungeon
  maxRooms: 40
  minRooms: 20
  minRequiredRooms: 1
  requiredRooms: forestcrypt_new_BurialChamber01, forestcrypt_new_BurialChamber02, forestcrypt_new_BurialChamber03, forestcrypt_new_BurialChamber04, forestcrypt_new_BurialChamber05
  themes: ForestCrypt
  doorTypes:
  - prefab: dungeon_forestcrypt_door
    connectionType: ''
  doorChance: 0.5
  maxTilt: 90
  spawnChance: 1
- name: DG_GoblinCamp
  algorithm: CampRadial
  maxRooms: 25
  minRooms: 15
  minRequiredRooms: 1
  themes: GoblinCamp
  doorTypes: []
  maxTilt: 25
  spawnChance: 1
  campRadiusMin: 15
  campRadiusMax: 30
  minAltitude: 1
  perimeterSections: 10
  perimeterBuffer: 2
- name: DG_MeadowsFarm
  algorithm: CampRadial
  maxRooms: 30
  minRooms: 20
  minRequiredRooms: 1
  themes: MeadowsFarm
  doorTypes: []
  maxTilt: 25
  spawnChance: 1
  campRadiusMin: 18
  campRadiusMax: 32
  minAltitude: 1
  perimeterSections: 10
- name: DG_MeadowsVillage
  algorithm: CampRadial
  maxRooms: 30
  minRooms: 20
  minRequiredRooms: 1
  themes: MeadowsVillage
  doorTypes: []
  maxTilt: 25
  spawnChance: 1
  campRadiusMin: 28
  campRadiusMax: 32
  minAltitude: 1
  perimeterSections: 10
- name: DG_SunkenCrypt
  algorithm: Dungeon
  maxRooms: 30
  minRooms: 20
  themes: SunkenCrypt
  doorTypes:
  - prefab: dungeon_sunkencrypt_irongate
    connectionType: ''
  doorChance: 0.3
  maxTilt: 90
  spawnChance: 1
- name: DG_Cave
  algorithm: Dungeon
  maxRooms: 64
  minRooms: 3
  minRequiredRooms: 3
  requiredRooms: cave_shrine_shrine01, cave_shrine_shrine02, cave_shrine_shrine03
  alternative: true
  themes: Cave
  doorTypes:
  - prefab: cloth_hanging_door_double
    connectionType: shrine
    chance: 0.8
  - prefab: caverock_ice_pillar_wall
    connectionType: ''
    chance: 0.2
  - prefab: caverock_ice_pillar_wall
    connectionType: water
  - prefab: caverock_ice_pillar_wall
    connectionType: ice
    chance: 0.2
  doorChance: 0.2
  maxTilt: 90
  spawnChance: 1
  interiorTransform: true
- name: DG_DvergrTown
  algorithm: Dungeon
  maxRooms: 96
  minRooms: 16
  minRequiredRooms: 1
  requiredRooms: dvergr_room_TREASURE, dvergr_room_TREASURE2
  alternative: true
  themes: DvergerTown
  doorTypes:
  - prefab: dvergrtown_creep_door
    connectionType: stone
    chance: 1
  - prefab: dvergrtown_creep_door
    connectionType: dvergr
    chance: 0.5
  - prefab: dvergrtown_slidingdoor
    connectionType: dvergr
    chance: 0.6
  - prefab: dvergrtown_wood_wall02
    connectionType: dvergr
    chance: 0.7
  doorChance: 0.9
  maxTilt: 90
  spawnChance: 1
  interiorTransform: true
- name: DG_DvergrBoss
  algorithm: Dungeon
  maxRooms: 512
  minRooms: 512
  minRequiredRooms: 1
  requiredRooms: dvergr_bossroom_COMPLETESTAIR04
  alternative: true
  themes: DvergerBoss
  doorTypes: []
  maxTilt: 90
  spawnChance: 1
  interiorTransform: true
